85 bug all published ros topics are empty
ll7/paf22 pull request #127
Opened 2022-12-30 10:47 UTC by timdreier

# Description

Add shortcuts for ROS commands.

Fixes #85 

## Time invested

1h 15m

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Does this PR introduce a breaking change?

No.

## Most important changes

That the shortcuts are working, e.g. `b5 rostopic list`.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (might be obsolete with CI later on)
- [x] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

2023-01-09 17:56 UTC, schwalga requested changes
The ability to run ros commands directly sounds like a great idea to me.
I tested some of the commands. 
While simple command like `b5 rostopic list` work just fine, I can't get more advanced commands (`b5 rostopic echo /carla/status`) to run without an error.
I'm not sure if this is due to user error or if changes are needed?

I think it would be good idea to add a few more commands to enable tools like `rqt_topic`, because as you mentioned in the documentation, for more complex tasks it is easier to use `b5 shell`.

2023-01-09 17:56 UTC, schwalga commented on build/tasks/ros.sh
> +}
```suggestion
}
task:rqt_graph() {
  task:roscommand "rqt_graph ${@}"
}
```
The commands to open a GUI (rqt_topic, rqt_plot,...) would be them most useful in my opinion.

2023-02-06 18:51 UTC, timdreier commented
Approved the requested changes and added the additional command to documentation.

Time invested: ~10 minutes

2023-02-07 19:00 UTC, schwalga commented
All in all, a nice PR that adds very helpful functionality.
While I would have liked a few more commands (`rqt_graph`, `rqt_topic`, ...), I think it is time to merge this PR.

2023-02-07 19:00 UTC, schwalga approved these changes

2023-02-07 19:01 UTC, merged